[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
# clap = "4.5.0"
libc = "0.2.153"
tungstenite = "0.21.0"
clap = { version = "4.5.0", features = ["cargo", "derive", ] }
async-std = "1.12.0"
strum = { version = "0.26.1", features = ["std", "derive", "strum_macros", "phf"] }
